### ISSUE TITLE
添加新接口，设置game_event。

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/tai-shang-world-generator#40]
悬赏价格：`¥200`
Routes:
```
# TODO: api about setting game event, create AdminController
```
从env环境中拿鉴权key：admin_key，作为`post`中的参数传递即可。
post body:
```
{
    admin_key: [admin_key],
    payload: [a-map]
}
```

补充：
> 是 linux 的 env。

**Comment by atlas-comstock** [comment]
@leeduckgo env环境是linux的env吗？ 需求很模糊诶，可以改一下吗

**Comment by kenspirit** [comment]
@leeduckgo 一个对外的接口，为什么从自己的 env 拿 key 来作为接收的 post body?

**Comment by leeduckgo** [comment]
> @leeduckgo env环境是linux的env吗？ 需求很模糊诶，可以改一下吗

已更新~

**Comment by leeduckgo** [comment]
> @leeduckgo 一个对外的接口，为什么从自己的 env 拿 key 来作为接收的 post body?

哈哈，一个懒人`update`数据库的方法。

**Comment by atlas-comstock** [comment]
@leeduckgo  Working on this
